### ISSUE TITLE
Finding puppetfiles in nested folders

### ISSUE THREAD

**Issue by Dumbaz** [nwops/puppet-retrospec#70]
My folder structure has subfolders in the manifest directory

```
manifests
├── common
│   ├── file11.pp
│   └── file12.pp
├── settings
│   ├── file21.pp
│   ├── file22.pp
│   └── file23.pp
├── dir3
├── init.pp
└── params.pp
```

retrospec does not find the puppetfiles in the subdirectories. Is there a way to make it search recursively?

**Comment by logicminds** [comment]
It should do this, let me investigate.
