### ISSUE TITLE
create spec files that conform to rubocop 

### ISSUE THREAD

**Issue by b4ldr** [nwops/puppet-retrospec#72]
Hi,  

First of all i love this project it saves me so much time, however i have one request i would like to make.  When i use `retrospec puppet` to generate some stock spec files it creates them using old ruby syntax which doesn't pass `bundle exec rake rubocop`.  the main issues i need to fix are 

  *  Missing magic comment
  *  using old style hash i.e. `:key => value`  instead of `key: value`
  * and having the following

```ruby
 it do
   is_expected to_contain_file('foobar')
   .with({
      :ensure => file,
     :content => 'foobar', 
   })
end
```

instead of 
```ruby
 it do
   is_expected to_contain_file('foobar').with(
      ensure: file,
     content: 'foobar' 
   )
end
```

I know this is probably low on your priority list of something to fix however if you could point me to the code i need to look at i would be happy to try and work up a pull request.

**Comment by logicminds** [comment]
Thanks for the praise.  Yea I think it is time to update the hash syntax.  Do you want to make a PR if i detail what to do?

**Comment by b4ldr** [comment]
yes more then happy to just need pointing in the right direction

**Comment by logicminds** [comment]
These are probably all (not 100% sure) the locations that would need to be changed.

This file recursively transforms the puppet code model to text output in rspec format.

So in this example you probably want to do something like:

```
if value[:required]
    ['  ', "#{value[:name].to_sym.inspect}", '=>', 'nil,', :break]
else
    ['  ', "##{value[:name].to_sym.inspect}", '=>', value[:default_value].inspect + ',', :break]
end
```

to the new hash format.  This code is the parameters that go into the `let(:params)` block

```
if value[:required]
    ['  ', "#{value[:name]}", ':', 'nil,', :break]
else
    ['  ', "##{value[:name]}", ':', value[:default_value].inspect + ',', :break]
end
```


https://github.com/nwops/puppet-retrospec/blob/master/lib/retrospec/plugins/v1/plugin/generators/serializers/rspec_dumper.rb#L164

https://github.com/nwops/puppet-retrospec/blob/master/lib/retrospec/plugins/v1/plugin/generators/serializers/rspec_dumper.rb#L213

https://github.com/nwops/puppet-retrospec/blob/master/lib/retrospec/plugins/v1/plugin/generators/serializers/rspec_dumper.rb#L235

https://github.com/nwops/puppet-retrospec/blob/master/lib/retrospec/plugins/v1/plugin/generators/serializers/rspec_dumper.rb#L230

**Comment by logicminds** [comment]
And you can test out the new code with the following test`bundle exec rspecspec/unit/generators/serializers/rspec_dumper_spec.rb`

**Comment by logicminds** [comment]
fixed in next release
