### ISSUE TITLE
git reference form config.yaml not passed to clone hook

### ISSUE THREAD

**Issue by witjoh** [nwops/puppet-retrospec#81]
After delving into the code, when teh config file is parsed, plugins::puppet::templates::ref is mapped to the :branch variable. 
When initializing the puppet plugin stuff, the branch argument of the 'setup_user_template' is assigned  
config_data[:ref].  This does not exists, because of the above mapping.

PR under way:

file retrospec/plugins/v1/plugin/puppet.rb line 32

**Comment by logicminds** [comment]
I was looking at this.  It appears like everything should work.  However, you are correct in that the ref is assigned to branch.  Ultimately this should not break anything because ref / branch essentially mean a commit to check out.  The variable names should be consistent though.  Instead of branch the variable name should be ref because it is very confusing.

```
 # creates and syncs the specifed user template diretory
      # returns: user_template_dir
      def setup_user_template_dir(user_template_directory = nil, git_url = nil, branch = nil)
        if user_template_directory.nil?
          user_template_directory = default_user_template_dir
        end
        template_dir = create_user_template_dir(user_template_directory)
        run_clone_hook(user_template_directory, git_url, branch)
        template_dir
      end
``` 

Of course if we change this method above, might as well change all the other references too.

```
 # runs the clone hook file
      # the intention of this method and hook is to download the templates
      # from an external repo. Because templates are updated frequently
      # and users will sometimes have client specific templates I wanted to
      # externalize them for easier management.
      def run_clone_hook(template_dir, git_url = nil, branch = nil)
        hook_file = clone_hook_file(template_dir)
        return unless File.exist?(hook_file)
        output = `ruby #{hook_file} #{template_dir} #{git_url} #{branch}`
        puts output
        if $CHILD_STATUS.success?
          puts "Successfully ran hook: #{hook_file}".info
          puts output.info
        else
          puts "Error running hook: #{hook_file}".fatal
          puts output.fatal
        end
      end
```

And the references in clone-hook under templates.  Can you refactor your PR with these changes I mentioned?  Essentially just change `branch` variables to `ref`.

I would like to get these changes in for the next release.

**Comment by witjoh** [comment]
Almost everything works, except updating the templates if you define a ref in ~/.retrospec/config.yaml.

I wanted to keep upstream the master, and the custom  retrospec-puppet-template a branch.  

As it is now, only the master branch can be checked out.  

Updated PR under way.

Thx for this great tool.

**Comment by witjoh** [comment]
what about this ?
replace 

    scm_branch = ENV['RETROSPEC_PUPPET_SCM_BRANCH'] || plugin_config['plugins::puppet::templates::ref'] || 'master'

to replace with    
          scm_ref = ENV['RETROSPEC_PUPPET_SCM_REF'] || ENV['RETROSPEC_PUPPET_SCM_BRANCH'] || plugin_config['plugins::puppet::templates::ref'] || 'master'
 
To be consistent in naming, the environment var should also be renamed to REF.  This way we are still backwards compatible.  Next major release the BRANCH could be removed.

**Comment by logicminds** [comment]
yea that looks great.

**Comment by witjoh** [comment]
and this we could leave at is : testing now

**Comment by logicminds** [comment]
Merged to master, will be in next release
